fieldLayouts:
  c78d3d14-3ed9-45be-8c43-1d631c306653:
    tabs:
      -
        elementCondition: null
        elements:
          -
            autocapitalize: true
            autocomplete: false
            autocorrect: true
            class: null
            disabled: false
            elementCondition: null
            id: null
            inputType: null
            instructions: null
            label: null
            max: null
            min: null
            name: null
            orientation: null
            placeholder: null
            readonly: false
            requirable: false
            size: null
            step: null
            tip: null
            title: null
            type: craft\fieldlayoutelements\entries\EntryTitleField
            uid: 6deb6a92-938a-48f8-b871-45de2bf55278
            userCondition: null
            warning: null
            width: 100
          -
            elementCondition: null
            fieldUid: 617ab8ee-5152-44e7-aea7-8a56157be4bf # Subheading
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: dfce5c7b-b1cd-44a6-bf86-c605622f4582
            userCondition: null
            warning: null
            width: 100
          -
            elementCondition: null
            fieldUid: f904b728-951f-4cbd-bb1a-984f00b2d9ea # Longform
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: ae890861-56a7-4ca9-b6bc-3e9285d5ef06
            userCondition: null
            warning: null
            width: 100
          -
            elementCondition: null
            fieldUid: 7c62bd61-4de6-4523-a736-1e917d13699e # Categories
            instructions: null
            label: 'Article Categories'
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 33e84d38-b195-4ba6-a91d-7879064f1c0b
            userCondition: null
            warning: null
            width: 100
        name: Content
        uid: 296396cd-df42-46aa-81ea-ebb0f7e155eb
        userCondition: null
      -
        elementCondition: null
        elements:
          -
            elementCondition: null
            fieldUid: 4a6ccf0d-3c6f-4845-8311-f049b4c1a304 # SEO
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: ded4af7b-14eb-4a78-8afc-657a2bde5701
            userCondition: null
            warning: null
            width: 100
        name: SEO
        uid: 160009ca-e06a-4886-8f41-be94ee7b0bb4
        userCondition: null
handle: articles_default
hasTitleField: true
name: Default
showStatusField: true
slugTranslationKeyFormat: null
slugTranslationMethod: site
sortOrder: 1
titleFormat: null
titleTranslationKeyFormat: null
titleTranslationMethod: site
