fieldLayouts:
  3bd0b9e8-ea81-4469-a5ff-b9ffc9551e38:
    tabs:
      -
        elementCondition: null
        elements:
          -
            autocapitalize: true
            autocomplete: false
            autocorrect: true
            class: null
            disabled: false
            elementCondition: null
            id: null
            inputType: null
            instructions: null
            label: null
            max: null
            min: null
            name: null
            orientation: null
            placeholder: null
            readonly: false
            requirable: false
            size: null
            step: null
            tip: null
            title: null
            type: craft\fieldlayoutelements\entries\EntryTitleField
            uid: 0ab81dc9-37b4-440d-a597-7a78f183565e
            userCondition: null
            warning: null
            width: 100
          -
            elementCondition: null
            fieldUid: f98c72b8-c1fd-47d1-b532-93b73afdfef1 # Heading
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 258f5d5c-21c4-48e4-9c30-715b5ee4e126
            userCondition: null
            warning: null
            width: 100
          -
            elementCondition: null
            fieldUid: fdf3a110-c29e-48e8-91cc-736a4d274fc4 # Body Simple Link
            instructions: null
            label: Contact
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 323f72f0-4a37-47c0-8b83-f8095a50f925
            userCondition: null
            warning: null
            width: 100
          -
            elementCondition: null
            fieldUid: 58413647-0403-4d88-8bf2-a21fbef39373 # Background Image
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: e49f1f52-78d9-4ffc-ac89-c41a4d11df57
            userCondition: null
            warning: null
            width: 100
        name: Content
        uid: 5c1bc9ec-3c3f-45a1-93a0-a68b0e4fdd0d
        userCondition: null
handle: contact
hasTitleField: false
name: Contact
showStatusField: true
slugTranslationKeyFormat: null
slugTranslationMethod: site
sortOrder: 1
titleFormat: '{section.name|raw}'
titleTranslationKeyFormat: null
titleTranslationMethod: site
