fieldLayouts:
  1d975a81-01aa-4850-98cc-705516bc0dc0:
    tabs:
      -
        elementCondition: null
        elements:
          -
            autocapitalize: true
            autocomplete: false
            autocorrect: true
            class: null
            disabled: false
            elementCondition: null
            id: null
            inputType: null
            instructions: null
            label: Name
            max: null
            min: null
            name: null
            orientation: null
            placeholder: null
            readonly: false
            requirable: false
            size: null
            step: null
            tip: null
            title: null
            type: craft\fieldlayoutelements\entries\EntryTitleField
            uid: 2ed5588d-90bf-4fb7-bfe6-cb8503ce5218
            userCondition: null
            warning: null
            width: 100
          -
            elementCondition: null
            fieldUid: f98c72b8-c1fd-47d1-b532-93b73afdfef1 # Heading
            instructions: null
            label: Role
            required: true
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 83a4c8d1-1759-4f56-a19f-cd1de1684871
            userCondition: null
            warning: null
            width: 100
          -
            elementCondition: null
            fieldUid: 00f81757-77f4-4683-ac92-0cb6223b8467 # Team
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: bf9979d2-13d9-4843-b5b8-6cf4013213c9
            userCondition: null
            warning: null
            width: 100
          -
            elementCondition: null
            fieldUid: a53e504a-eefb-4fd7-ab18-74d4edbb639b # LinkedIn Profile
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: c4ca1fd3-7ca0-4082-b08d-c49f85a71e85
            userCondition: null
            warning: null
            width: 100
          -
            elementCondition: null
            fieldUid: b0029eaa-acd8-409d-bcfe-bf589b7dc1e3 # Profile Photo
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 0439f7a4-2c79-4de5-839d-7b09cc775eb5
            userCondition: null
            warning: null
            width: 100
          -
            elementCondition: null
            fieldUid: 430f7f99-e13e-4618-bc6d-e990026c660d # Body Simple
            instructions: null
            label: Bio
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: a1a12e20-a59f-49c7-928c-7f3ea4ebb800
            userCondition: null
            warning: null
            width: 100
        name: Content
        uid: c80865f5-0e9a-4258-85f5-13430e64fdd8
        userCondition: null
      -
        elementCondition: null
        elements:
          -
            elementCondition: null
            fieldUid: 4a6ccf0d-3c6f-4845-8311-f049b4c1a304 # SEO
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 2788794e-088a-4f74-bd2a-886001345c46
            userCondition: null
            warning: null
            width: 100
        name: SEO
        uid: a1e9b85b-d471-4d7e-a902-5ef37e53788e
        userCondition: null
handle: people_default
hasTitleField: true
name: Default
showStatusField: true
slugTranslationKeyFormat: null
slugTranslationMethod: site
sortOrder: 1
titleFormat: null
titleTranslationKeyFormat: null
titleTranslationMethod: site
