childBlocks: null
color: null
conditions: null
description: ''
enabled: true
entryType: null
field: 0aa7bf8b-d4e1-4016-bc62-588296598ca8 # Blocks
fieldLayouts:
  b6d42ec3-ca8e-4621-b452-e447b4f9ca37:
    cardThumbAlignment: end
    tabs:
      -
        elementCondition: null
        elements:
          -
            dateAdded: null
            editCondition: null
            elementCondition: null
            elementEditCondition: null
            fieldUid: 5daca263-757f-4613-bf47-9152f741e09d # Eyebrow
            handle: null
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 74a35e16-1560-4919-a5be-2b5f53cfea1e
            userCondition: null
            warning: null
            width: 100
          -
            dateAdded: null
            editCondition: null
            elementCondition: null
            elementEditCondition: null
            fieldUid: f98c72b8-c1fd-47d1-b532-93b73afdfef1 # Heading
            handle: null
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: b8e7e26f-8fc1-4fc1-9359-c5825d816d84
            userCondition: null
            warning: null
            width: 100
          -
            dateAdded: null
            editCondition: null
            elementCondition: null
            elementEditCondition: null
            fieldUid: f7d50232-1776-417e-989f-c93bb87683d1 # Copy
            handle: null
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: c7ffe56e-49f7-4233-93eb-bb1f3cb1aed6
            userCondition: null
            warning: null
            width: 100
          -
            dateAdded: null
            editCondition: null
            elementCondition: null
            elementEditCondition: null
            fieldUid: 5e675d35-5cbe-472c-95d9-587691f3dda2 # Checklist
            handle: null
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 3d4ef90b-df74-4ad3-b90a-6063abe2f4eb
            userCondition: null
            warning: null
            width: 100
          -
            dateAdded: null
            editCondition: null
            elementCondition: null
            elementEditCondition: null
            fieldUid: 35e65122-056f-4a98-8b50-7ac4d1fc8e4a # Lightswitch
            handle: null
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 934c34f0-de9e-43c4-92c7-fb4302842ee7
            userCondition: null
            warning: null
            width: 100
        name: Content
        uid: 9cca5c99-c3fe-4795-9764-98058b1129dc
        userCondition: null
    thumbFieldKey: null
group: null
groupChildBlockTypes: true
handle: checklist
icon: null
iconFilename: ''
ignorePermissions: true
maxBlocks: 0
maxChildBlocks: 0
maxSiblingBlocks: 0
minBlocks: 0
minChildBlocks: 0
minSiblingBlocks: 0
name: Checklist
topLevel: true
