childBlocks: null
color: null
conditions: null
description: ''
enabled: true
entryType: null
field: 0aa7bf8b-d4e1-4016-bc62-588296598ca8 # Blocks
fieldLayouts:
  fd738aa8-1fb6-4a50-829f-35dbad4bc8a0:
    cardThumbAlignment: end
    tabs:
      -
        elementCondition: null
        elements:
          -
            dateAdded: null
            editCondition: null
            elementCondition: null
            elementEditCondition: null
            fieldUid: 5daca263-757f-4613-bf47-9152f741e09d # Eyebrow
            handle: null
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 512501bd-40f1-453b-8e12-3c7781fc3b19
            userCondition: null
            warning: null
            width: 100
          -
            dateAdded: null
            editCondition: null
            elementCondition: null
            elementEditCondition: null
            fieldUid: f98c72b8-c1fd-47d1-b532-93b73afdfef1 # Heading
            handle: null
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: edd83c29-3463-4559-927f-f99528b9529e
            userCondition: null
            warning: null
            width: 100
          -
            dateAdded: null
            editCondition: null
            elementCondition: null
            elementEditCondition: null
            fieldUid: f7d50232-1776-417e-989f-c93bb87683d1 # Copy
            handle: null
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: c47591a8-ad28-4a37-b409-8a609a40b547
            userCondition: null
            warning: null
            width: 100
          -
            dateAdded: null
            editCondition: null
            elementCondition: null
            elementEditCondition: null
            fieldUid: 677709f9-0b6b-4d19-969c-0495c252dcca # Image
            handle: null
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 662f0ff5-3756-4cd1-85d3-9a5dc9375513
            userCondition: null
            warning: null
            width: 100
        name: Content
        uid: 5062a844-2187-4db8-a7d8-483d0ed99c7e
        userCondition: null
    thumbFieldKey: null
group: null
groupChildBlockTypes: true
handle: sectorsThemes
icon: null
iconFilename: ''
ignorePermissions: true
maxBlocks: 0
maxChildBlocks: 0
maxSiblingBlocks: 0
minBlocks: 0
minChildBlocks: 0
minSiblingBlocks: 0
name: 'Sectors & Themes'
topLevel: true
