columnSuffix: null
contentColumnType: string
handle: additionalLogos
instructions: null
name: 'Additional Logos'
searchable: false
settings:
  entryTypes:
    -
      uid: eb817486-091f-4ed8-ab34-bd1c0f0f7a7e
  maxEntries: 2
  minEntries: null
  propagationKeyFormat: null
  propagationMethod: all
  viewMode: blocks
translationKeyFormat: null
translationMethod: site
type: craft\fields\Matrix
