columnSuffix: null
contentColumnType: string
handle: backgroundImage
instructions: null
name: 'Background Image'
searchable: false
settings:
  allowSelfRelations: false
  allowSubfolders: true
  allowUploads: true
  allowedKinds:
    - image
  branchLimit: null
  defaultUploadLocationSource: 'volume:35279a43-bca0-475d-a8da-25e0ecbccac7' # Images
  defaultUploadLocationSubpath: null
  localizeRelations: false
  maintainHierarchy: false
  maxRelations: 1
  minRelations: null
  previewMode: full
  restrictFiles: true
  restrictLocation: true
  restrictedDefaultUploadSubpath: backgrounds
  restrictedLocationSource: 'volume:35279a43-bca0-475d-a8da-25e0ecbccac7' # Images
  restrictedLocationSubpath: null
  selectionLabel: null
  showSiteMenu: true
  showUnpermittedFiles: false
  showUnpermittedVolumes: false
  sources: '*'
  targetSiteId: null
  validateRelatedElements: false
  viewMode: list
translationKeyFormat: null
translationMethod: site
type: craft\fields\Assets
