columnSuffix: mmecerrf
contentColumnType: string(5)
handle: backgroundColor
instructions: null
name: 'Background Color'
searchable: false
settings:
  columnType: null
  options:
    -
      __assoc__:
        -
          - label
          - White
        -
          - value
          - white
        -
          - default
          - '1'
    -
      __assoc__:
        -
          - label
          - Gray
        -
          - value
          - gray
        -
          - default
          - ''
translationKeyFormat: null
translationMethod: none
type: craft\fields\Dropdown
