columnSuffix: lzgnplmz
contentColumnType: text
handle: bodySimple
instructions: null
name: 'Body Simple'
searchable: true
settings:
  availableTransforms: ''
  availableVolumes: ''
  ckeConfig: f843f4f4-4cf3-4c19-95bf-b535238a14c5 # Simple
  columnType: text
  defaultTransform: null
  enableSourceEditingForNonAdmins: false
  purifierConfig: null
  purifyHtml: true
  showUnpermittedFiles: false
  showUnpermittedVolumes: false
  showWordCount: false
  wordLimit: null
translationKeyFormat: null
translationMethod: none
type: craft\ckeditor\Field
