columnSuffix: dkcxpefh
contentColumnType: text
handle: bodySimpleLink
instructions: null
name: 'Body Simple Link'
searchable: false
settings:
  availableTransforms: ''
  availableVolumes: ''
  ckeConfig: 2ba5d709-2894-4970-9b9f-15c32d972487 # Simple Link
  columnType: text
  defaultTransform: null
  enableSourceEditingForNonAdmins: false
  purifierConfig: null
  purifyHtml: true
  showUnpermittedFiles: false
  showUnpermittedVolumes: false
  showWordCount: false
  wordLimit: null
translationKeyFormat: null
translationMethod: none
type: craft\ckeditor\Field
