columnSuffix: rzjivlzh
contentColumnType: text
handle: checklist
instructions: null
name: Checklist
searchable: false
settings:
  addRowLabel: 'Add a row'
  columnType: text
  columns:
    __assoc__:
      -
        - col1
        -
          __assoc__:
            -
              - heading
              - Detail
            -
              - handle
              - detail
            -
              - width
              - ''
            -
              - type
              - singleline
  defaults:
    -
      __assoc__:
        -
          - col1
          - ''
  maxRows: null
  minRows: 1
  staticRows: false
translationKeyFormat: null
translationMethod: none
type: craft\fields\Table
