columnSuffix: dniwxlpf
contentColumnType: boolean
handle: ctaBackground
instructions: null
name: 'CTA Background'
searchable: false
settings:
  default: false
  offLabel: Gray
  onLabel: White
translationKeyFormat: null
translationMethod: none
type: craft\fields\Lightswitch
