columnSuffix: null
contentColumnType: string
handle: dealStatus
instructions: null
name: 'Deal Status'
searchable: false
settings:
  allowSelfRelations: false
  branchLimit: null
  localizeRelations: false
  maintainHierarchy: false
  maxRelations: 1
  minRelations: null
  selectionLabel: null
  showSiteMenu: true
  sources:
    - 'section:270a2002-271e-4b2b-a058-1cd15565944c' # Deal Status
  targetSiteId: null
  validateRelatedElements: false
  viewMode: null
translationKeyFormat: null
translationMethod: site
type: craft\fields\Entries
