columnSuffix: ujkxfiqv
contentColumnType: string(255)
handle: linkedinProfile
instructions: ' '
name: 'LinkedIn Profile'
searchable: false
settings:
  maxLength: 255
  types:
    - url
translationKeyFormat: null
translationMethod: none
type: craft\fields\Url
