columnSuffix: aqpdblyd
handle: logoUrl
instructions: null
name: 'Additional Logos - Logos - Logo Url'
searchable: false
settings:
  fullGraphqlData: false
  maxLength: 255
  showLabelField: false
  types:
    - url
translationKeyFormat: null
translationMethod: none
type: craft\fields\Link
