columnSuffix: esmqnkhk
contentColumnType: string(512)
handle: mapUrl
instructions: 'Paste a Maps link `https://www.google.com/maps/place...`'
name: 'Map URL'
searchable: false
settings:
  maxLength: 512
  types:
    - url
translationKeyFormat: null
translationMethod: none
type: craft\fields\Url
