columnSuffix: xqecwcye
contentColumnType: text
handle: seo
instructions: null
name: SEO
searchable: false
settings:
  elementDisplayPreviewType: none
  facebookEnabledFields: ''
  facebookTabEnabled: ''
  generalEnabledFields:
    - seoTitle
    - seoDescription
    - seoImage
  generalTabEnabled: '1'
  sitemapEnabledFields: ''
  sitemapTabEnabled: ''
  twitterEnabledFields:
    - seoPreview
  twitterTabEnabled: ''
translationKeyFormat: null
translationMethod: none
type: nystudio107\seomatic\fields\SeoSettings
