columnSuffix: pusvvksb
contentColumnType: string(255)
handle: videoUrl
instructions: 'Vimeo sharing link e.g. `https://vimeo.com/173365667`'
name: 'Video URL'
searchable: false
settings:
  maxLength: 255
  types:
    - url
translationKeyFormat: null
translationMethod: none
type: craft\fields\Url
