columnSuffix: lhyxokmk
contentColumnType: string(255)
handle: websiteLink
instructions: null
name: 'Website Link'
searchable: false
settings:
  maxLength: 255
  types:
    - url
translationKeyFormat: null
translationMethod: none
type: craft\fields\Url
