defaultPlacement: end
enableVersioning: true
entryTypes:
  -
    handle: default
    uid: 907bb579-cb4c-4038-a02f-29e4fef867b3 # Default
handle: articles
maxAuthors: 1
name: Articles
previewTargets:
  -
    label: 'Primary entry page'
    refresh: '1'
    urlFormat: '{url}'
propagationMethod: all
siteSettings:
  434e47c7-7222-4db0-a9b4-d7ed1ba78376: # $CRAFT_SYSTEM_NAME
    enabledByDefault: true
    hasUrls: true
    template: news/entry
    uriFormat: 'news/{slug}'
type: channel
