defaultPlacement: end
enableVersioning: true
entryTypes:
  -
    uid: 896da32e-f295-43a6-937c-2642ca6f9f0b # 404
handle: error
maxAuthors: 1
name: '404'
propagationMethod: all
siteSettings:
  434e47c7-7222-4db0-a9b4-d7ed1ba78376: # $CRAFT_SYSTEM_NAME
    enabledByDefault: true
    hasUrls: false
    template: null
    uriFormat: null
type: single
