defaultPlacement: end
enableVersioning: true
entryTypes:
  -
    uid: ce32a7d2-9bc8-4e9c-91d1-2a77a9af66d6 # Homepage
handle: homepage
maxAuthors: 1
name: Homepage
previewTargets:
  -
    label: 'Primary entry page'
    refresh: '1'
    urlFormat: '{url}'
propagationMethod: all
siteSettings:
  434e47c7-7222-4db0-a9b4-d7ed1ba78376: # $CRAFT_SYSTEM_NAME
    enabledByDefault: true
    hasUrls: true
    template: pages/default
    uriFormat: __home__
type: single
