defaultPlacement: end
enableVersioning: true
entryTypes:
  -
    handle: default
    uid: ec7c30b5-0eab-4abb-9942-0b1bda47db85 # Default
handle: newsCategories
maxAuthors: 1
name: 'News Categories'
propagationMethod: all
siteSettings:
  434e47c7-7222-4db0-a9b4-d7ed1ba78376: # $CRAFT_SYSTEM_NAME
    enabledByDefault: true
    hasUrls: false
    template: null
    uriFormat: null
structure:
  maxLevels: null
  uid: ee1cbb6b-21a2-4074-928d-57d4f4b0d886
type: structure
