defaultPlacement: end
enableVersioning: true
entryTypes:
  -
    handle: default
    uid: 4d273976-278c-4064-9e24-ef8dd98e62ae # Default
handle: people
maxAuthors: 1
name: People
previewTargets:
  -
    label: 'Primary entry page'
    refresh: '1'
    urlFormat: '{url}'
propagationMethod: all
siteSettings:
  434e47c7-7222-4db0-a9b4-d7ed1ba78376: # $CRAFT_SYSTEM_NAME
    enabledByDefault: true
    hasUrls: true
    template: team/entry
    uriFormat: 'team/{slug}'
structure:
  maxLevels: 1
  uid: aeb5af4d-07cc-47c8-82f7-72a981237f93
type: structure
