defaultPlacement: end
enableVersioning: true
entryTypes:
  -
    uid: e8be3e0f-0b95-4872-a895-fb7cbd64503a # Investment Themes
handle: strategy
maxAuthors: 1
name: 'Investment Themes'
previewTargets:
  -
    label: 'Primary entry page'
    refresh: '1'
    urlFormat: '{url}'
propagationMethod: all
siteSettings:
  434e47c7-7222-4db0-a9b4-d7ed1ba78376: # $CRAFT_SYSTEM_NAME
    enabledByDefault: true
    hasUrls: true
    template: pages/default
    uriFormat: investment-themes
type: single
