defaultPlacement: end
enableVersioning: true
entryTypes:
  -
    handle: default
    uid: c1d67c47-3edc-40c8-b912-439b27823a2d # Default
handle: teams
maxAuthors: 1
name: Teams
propagationMethod: all
siteSettings:
  434e47c7-7222-4db0-a9b4-d7ed1ba78376: # $CRAFT_SYSTEM_NAME
    enabledByDefault: true
    hasUrls: false
    template: null
    uriFormat: null
structure:
  maxLevels: 1
  uid: eb6b3d73-e1f9-4e31-b293-fe2e953ff2f9
type: structure
