defaultPlacement: end
enableVersioning: true
entryTypes:
  -
    uid: c009ff8c-5188-4dc8-a4e1-3d8548fe4c9f # Team
handle: team
maxAuthors: 1
name: Team
previewTargets:
  -
    label: 'Primary entry page'
    refresh: '1'
    urlFormat: '{url}'
propagationMethod: all
siteSettings:
  434e47c7-7222-4db0-a9b4-d7ed1ba78376: # $CRAFT_SYSTEM_NAME
    enabledByDefault: true
    hasUrls: true
    template: team/index
    uriFormat: team
type: single
