defaultPlacement: end
enableVersioning: true
entryTypes:
  -
    handle: default
    uid: b727d412-f255-4e92-bef2-3529efe9f0d1 # Default
handle: themes
maxAuthors: 1
name: Themes
propagationMethod: all
siteSettings:
  434e47c7-7222-4db0-a9b4-d7ed1ba78376: # $CRAFT_SYSTEM_NAME
    enabledByDefault: true
    hasUrls: false
    template: null
    uriFormat: null
structure:
  maxLevels: 1
  uid: 71c8d015-a9b3-4763-aff2-cdf2f6650e20
type: structure
